### ISSUE TITLE
Error: "cannot find GOROOT directory"

### ISSUE THREAD

**Issue by ditek** [grandcolline/golang-github-actions#14]
I think there's a bug when running on subdirectories.
Running `staticcheck ./...` locally works. I added the action to my Yaml file as:

```yaml
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v1
        with:
          go-version: 1.16
      - run: go test ./...
      - name: staticcheck
        uses: grandcolline/golang-github-actions@v1.1.0
        with:
          run: staticcheck
          flags: ./...
          token: ${{ secrets.GITHUB_TOKEN }}
```

This is the output of the action:

<img width="816" alt="image" src="https://user-images.githubusercontent.com/10835824/117983664-74423000-b337-11eb-9a85-4feaebf88fcd.png">
